#!/usr/bin/env python3
"""GenApep IPO Plan v2 -> ipo-plan-v2.md + GenApep_IPO_Plan_v2.docx.

Full revision of the IPO plan on the September-2026 verified evidence:
Eyesel statutory FY2024/FY2025 financials, the FirstVitals DD report
(Hayley Zen, 2026-09-03), the FirstVitals/ProteusDx cap table
(2026-09-02), and the strategy meeting summary. Supersedes the route
strategy and every FirstVitals representation of the draft IPO-framework
MOU. Includes the viability evaluation from the WBI seat and the Eyesel
seat. Prepared from a 7-agent analysis with adversarial verification.
"""
from docx import Document
from docx.shared import Pt, RGBColor, Inches
from docx.enum.text import WD_ALIGN_PARAGRAPH
from docx.enum.table import WD_TABLE_ALIGNMENT

DIR = "/home/user/gamification/synexo/"
NAVY = RGBColor(0x1B, 0x33, 0x55); GREY = RGBColor(0x55, 0x55, 0x55)
ACCENT = RGBColor(0x2E, 0x86, 0xC1); RED = RGBColor(0xC0, 0x39, 0x2B)

CONF = ("PRIVATE & CONFIDENTIAL — for the boards of WBI and Eyesel. Not for release to "
        "FirstVitals or any third party. Supersedes the route strategy and all FirstVitals "
        "representations of the draft IPO-framework MOU.")
DISCLAIMER = ("Prepared 16 September 2026 on the evidence listed in Section 1. Non-binding; not "
              "legal, tax, accounting or securities advice; regulatory statements require written "
              "confirmation by counsel. FX shown at both ₩1,400/$ and ₩1,500/$ where material.")

# =============================== content ===============================

EVIDENCE = [
    ["Eyesel statutory income statement FY2025/FY2024 (제19기/제18기)", "Verified financials of Eyesel — closes the open Eyesel-data item"],
    ["Eyesel retained-earnings appropriation statement", "₩10.36B unappropriated retained earnings; ₩300M FY2024-cycle dividend"],
    ["Due Diligence Strategic Report on FirstVitals (Hayley Zen → WBI, 2026-09-03)", "FirstVitals history, pivot, Reg A+ status, Rule 3-05 analysis"],
    ["FirstVitals/ProteusDx cap table (2026-09-02, generated by Ernest Lee)", "Ownership 94.63% one holder; $500K lifetime capital; 7.5M-share unissued pool"],
    ["Strategy meeting summary (Sidney Tam org.; EyeSel Mr Kim, Theresa Jang)", "US-vs-Korea routes, $2M bridge math, FirstVitals claims as pitched"],
]

FVH_CLAIMS = [
    ["“SEC filer since Dec 2024 / listed vehicle / maintains reporting status”", "CONTRADICTED", "EDGAR shows a Form 1-A Reg A+ Tier 2 crowdfunding offering (target up to $20.74M, KoreConX portal, Andes Capital intermediary). No S-1. A Reg A+ issuer is NOT an Exchange Act reporting company absent Form 8-A/Form 10."],
    ["Operating GLP-1 Bridge program ($2.2M’26 → $16.7M’27; MRR $1.59M/mo)", "CONTRADICTED as operating revenue", "FirstVitals abandoned its RPM/CCM services in the 2024 pivot to ProteusDx (GI capsule-endoscopy AI, Phase-1 pilot, pre-revenue per its own internal papers). The proforma is an unvalidated plan; zero verified enrollment or claims data."],
    ["“Medicare network contracts” / “GLP-1 technology”", "UNVERIFIED / CONTRADICTED", "History was Hawaii MEDICAID, and those services were abandoned; no GLP-1 content in the internal papers. Posture: demand the contracts be produced."],
    ["“$75M valuation cap”", "UNSUPPORTABLE", "Lifetime capital raised = one $500K convertible note; pre-revenue; no priced round or institutional investor. ($75M is the Reg A+ Tier 2 REGULATORY ceiling per 12 months — the likely source of the number; the current offering targets $20.74M.)"],
    ["“List in the US by mid-2027”", "CONTRADICTED", "SEC Rule 3-05: acquiring WBI+Eyesel (combined FY2025A ~$10.9M revenue) into a pre-revenue registrant is significant at the maximum tier → up to 2 years PCAOB-audited US GAAP financials of the Korean companies in any S-1 (or Form 1-A Part F/S) → 12–18 months minimum. Even the Reg A+→Form 8-A direct-listing path fails exchange initial-listing standards and Nasdaq’s 2-year operating-history rule for Reg A issuers [counsel to confirm]."],
    ["Implied FVH value $10–13M (draft MOU) / $5–10–13M scenarios (briefing)", "OVERSTATED ≥ 5×", "Assessed supportable planning value: ~$0–2M, possibly negative after the $500K convertible note (terms unverified) and contingent exposures (retail-offering compliance, FDA/telehealth marketing gap). Basis: pre-revenue per the DD report and the counterparty's own cap table — pending Form 1-K/1-SA confirmation (gate-zero). Benchmark: a clean new US topco costs well under $100K."],
]

FVH_STRUCTURE_TRAPS = [
    "Ownership: 6,341,625 shares outstanding; Ernest Gin Lee 6,001,000 = 94.63%; eight friends-and-family holders; no preferred; no institutional money. Entity-name chain unresolved: “First Vital Health and Wellness Inc” (draft MOU) vs “FirstVital(s), Inc.” (DD) vs “ProteusDx” (cap-table title) — the counterparty of record must be tied to the 1-A filer before anything is signed.",
    "The 7,500,000-share 2024 Omnibus pool (54.18% of 13,841,625 fully diluted, zero issued) is the controlling trap: the draft MOU’s “75%” computed on outstanding shares falls to 57.9% fully diluted if the pool is granted — a unilateral 17-point haircut controlled by the FVH-side board. Any term sheet must make pool cancellation (or a hard cap with block consent) a condition precedent.",
    "The $500K convertible note is a gate-zero document, not a footnote: holder identity (if Lee or an affiliate, it is self-dealing paper), drawn amount, discount/cap, maturity and default status must be produced. A low-cap note can out-dilute even the option pool.",
    "The cap table is self-generated by the counterparty (Ernest Lee, 2026-09-02) and unaudited. If Reg A+ retail money was actually received, the cap table is materially wrong; if not, the offering has raised ~nothing against its $20.74M target. The Form 1-K/1-SA filings resolve which — obtain them.",
]

EYESEL_TABLE = [
    ["Revenue", "₩10,460.2M = $7.47M/$6.97M", "₩9,468.4M = $6.76M/$6.31M", "+10.5% YoY; exports ₩5,294.0M = 50.6% of sales, +19.5% YoY"],
    ["Gross profit", "₩4,995.2M (47.8%)", "₩5,104.9M (53.9%)", "-6.1pp mix/price compression ≈ ₩642M margin effect at FY2025 volume"],
    ["Operating profit", "₩1,841.2M = $1.32M (17.6%)", "₩2,660.8M = $1.90M (28.1%)", "-30.8%: commissions +₩393.5M (10.5× — DD the counterparty), salaries +₩342.5M, depreciation +₩108.7M"],
    ["Net income", "₩2,048.1M = $1.46M", "₩2,724.5M = $1.95M", "FY2025 incl. one-off ₩301.2M PP&E disposal gain; ETR only 4.1% (SME/R&D credits)"],
    ["Retained earnings c/f", "₩10,358.8M = $7.40M", "₩8,310.2M", "₩300M cash dividend in FY2024 cycle; FY2025 proposal: zero dividend"],
]

EYESEL_READS = [
    "The 51:49 basis HOLDS and the equalisation condition can be closed: FY2025 revenue vs the $8.0M peg = -6.6% @₩1,400 and -12.8% @₩1,500 — inside the 15% band at both conventions. Record the statutory figures on the face of Amendment No. 1 and declare the condition satisfied.",
    "Two drafting locks before signing: (a) FIX THE FX CONVENTION (KRW-denominated peg or a stated rate) — above ₩1,538/$ the same actuals breach the band; (b) PIN THE REFERENCE PERIOD to FY2025 statutory — FY2024 revenue @₩1,400 is -15.5% vs the peg, i.e., OUTSIDE the band on a different period selection.",
    "On earnings the 51% is conservative: Eyesel is ~2.2× WBI on revenue, ~8.4× on net income and ~10.7× on operating profit (WBI’s ₩172.3M OP is an implied figure — verify against the NTS filing before any board table). A value-proportional re-test would move the split TOWARD Eyesel; WBI’s 49% is properly defended on forward contribution (MM Studio ramp, AI-peptide/DPW technology, US execution), not on trailing numbers.",
    "The “~$15M Eyesel revenue” figure in the draft IPO MOU lineage is contradicted (~2× overstatement) and is purged from all documents in this revision.",
    "Eyesel is the group’s auditable profit anchor — but its books are on the K-SME standard, the longest conversion path to PCAOB US GAAP/IFRS. Its board must see a costed audit quote before the Q4-2026 engagement; and retained earnings are not cash — obtain the balance sheet (interest income fell ₩153.5M→₩62.2M while depreciation tripled, implying cash was deployed into capex/property).",
]

WBI_FIGURES = [
    ["WBI FY2025 actual (NTS-certified)", "₩4,802.7M ≈ $3.43M @1,400", "The only verified WBI revenue figure"],
    ["WBI-side 2026 plan", "$7.59M (core $4.69M + MM Studio $2.90M)", "Requires ~2.2× in-year growth — evidence pack needed"],
    ["Combined WBI+Eyesel FY2025A", "₩15,262.9M ≈ $10.90M @1,400 / $10.18M @1,500", "The correct Rule 3-05 numerator"],
    ["“$11.7M 2026 WBI exosome revenue” (DD report)", "DOES NOT RECONCILE — correct at source", "3.4× the FY2025 actual; candidate sources of the error: combined FY2025A $10.2–10.9M (@₩1,500/₩1,400) or the JV plan's 2025 combined PLANNING figure $11.43M. Do not circulate the DD until fixed."],
]

ROUTES = [
    ["A — Own US listing (GenApep Holdings F-1)",
     "Foreign private issuer: IFRS-as-issued, confidential DRS, EGC 2-year financials. Audits Q4-2026→late-2027; DRS end-2027/early-2028; pricing H2-2028 with the ~$20M primary raise at pricing.",
     "DEFAULT — and now also the FASTEST US path. Conditional on: sponsor pre-money for the $2M bridge demonstrably above ~$25–35M (at ~$18M pre, WBI holders are underwater vs their $89.75 basis), US opex discipline, US CEO identified."],
    ["B — Combine with FirstVitals",
     "Not a reporting company; combination confers no listing status and raises no capital; pre-revenue per DD/cap table (1-K/1-SA confirmation pending); Rule 3-05 audit wall applies identically; US GAAP (not IFRS); reverse-merger seasoning on any exchange application; 54.18%-FD unissued pool; zero operational synergy (DD: “financial splicing”).",
     "REJECT AS PITCHED. Keep alive only as (i) an optional cheap-shell purchase at verified value (~$0–2M) with the pool cancelled and gate-zero verification passed, executed through Addendum A block entry; or (ii) an arm’s-length US commercial-channel discussion (their clinics as a customer), no equity."],
    ["C — Korea listing (KOSDAQ)",
     "Eyesel’s verified profitability (₩1.84B OP, ₩10.36B retained earnings, dividend history) fits KOSDAQ profit tracks on trailing numbers; K-IFRS conversion instead of US GAAP; no $300–500K/yr US opex, no US CEO problem; eliminates the Korean cross-border swap-tax/FX problem for BOTH shareholder bodies.",
     "PROMOTE to a formally developed parallel track. Cash timing comparable to Route A (H2-2028/2029); the credible fallback that disciplines every US-sponsor valuation conversation."],
]

PLAN_STEPS = [
    ["1. Sign Amendment No. 1 — with two locks", "Now",
     "Eyesel’s verified FY2025 closes the equalisation condition (inside the 15% band). Add: FX convention fixed; reference period pinned to FY2025 statutory; no-leakage/permitted-distributions covenant from signing to closing; written board confirmation of the Eyesel principal (Mr Kim per the meeting vs Mr. Park per the 12-Aug MOU)."],
    ["2. Execute the $2M bridge — route-independent", "By end-2026",
     "The only financing that addresses the mid-2028 pressure point. Define the receiving entity (the holdco once formed). Accept ~10% dilution only if no sponsor validates a higher pre-money; walk-away floor ~$25M pre."],
    ["3. Appoint the PCAOB-registered auditor — dual-scoped", "Q4 2026 (≤3.5 months away)",
     "IFRS primary basis with a costed US GAAP option — keeps Routes A and C open at lowest conversion cost. Obtain a fee quote for the K-SME→IFRS/US GAAP conversion of Eyesel BEFORE engagement; the audit is the critical path under every route."],
    ["4. FirstVitals gate-zero — before any term discussion", "Before/at the Ernie Lee meetings",
     "CIK + full EDGAR index; 1-A qualification status and amounts ACTUALLY sold; Form 8-A/Form 10 check; Form 1-K/1-SA cash-runway review; the $500K note (holder, terms, default status); entity-name chain to the 1-A filer; reconcile the internal-papers-vs-public-website narrative gap under NDA; then a written US securities-counsel memorandum (reporting status, shell classification/Rule 144(i), seasoning rules)."],
    ["5. Stage-1 execution unchanged", "Q3-2026 → Q1–Q2 2027",
     "Cayman holdco + GenApep Korea; definitive SHA + sweat-pool KPI schedule; share exchange Q1–Q2 2027 through the holdco block (one collective Korean FX filing, one taxable event at pre-listing value). Note: the draft MOU’s “issue 75% before Dec 2026” was never executable against this tax-compliant sequence."],
    ["6. Route decision at the gate", "When gates report",
     "Route A default; Route C developed in parallel with a KOSDAQ readiness memo; Route B only on the repriced, verified, pool-cancelled basis through Addendum A (block entry, fairness opinion, disinterested approval)."],
]

WBI_PS = [
    ["Today (basis)", "$89.75", "111,448 shares (incl. 5% placement 5,572) ≈ $10.0M"],
    ["Route A @ $100M post ($80M pre + $20M raise)", "$264–285", "45.3% × 65–70% retained after bridge+IPO dilution"],
    ["Route A @ $40–50M post (sponsor-conservative)", "$106–142", "Sponsor validation of the valuation is the load-bearing condition"],
    ["Route A @ ~$18M pre (forced bridge)", "~$73", "UNDERWATER vs basis — the walk-away scenario"],
    ["Route C (KOSDAQ) @ 15–25× combined NI", "$98–167", "₩2,291M combined FY2025A NI; no US opex/GAAP drag"],
    ["Route B @ honest FVH ~$1M, pool cancelled", "~$316*", "*Not dilution-comparable: assumes the same $80M cap with NO financing dilution and FVH contingencies at zero — read as an upper bound only"],
    ["Route B @ FVH $10M / @ claimed $75M cap", "$253 / $103", "Every dollar conceded to FVH above verified value is a direct transfer from GenApep shareholders"],
]

WBI_VIEW = [
    ["Ranked: 1st Route A (conditional), 2nd Route C, 3rd Route B (reject as pitched)",
     "Route A is the only route where WBI’s 45.3% compounds into ~30% of a listed company on the JV’s own story. Its viability hinges on two facts to force into the open now: a sponsor term sheet above ~$25–35M pre-money, and the funding bridge across mid-2028. Route C is the disciplined fallback with $98–167/share and far lower cost. Route B as pitched (at $75M-cap framing) takes WBI holders to ~14% and ~$103/share — a value transfer to a 94.63% single holder."],
    ["Symmetric verification duty",
     "Eyesel now holds statutory verification; WBI’s 49% rests on an implied OP figure, a 2026 plan needing ~2.2× in-year growth, and an MM Studio ramp with no cited contract evidence. Produce WBI’s evidence pack (NTS filing, H1-2026 actuals, MM Studio contracts/pipeline) before Eyesel demands it."],
    ["Shareholder-correction duty",
     "The Chinese one-pager already circulated to WBI shareholders carries the ~$10M FVH verified-value scenario and the $16.7M GLP-1 forecast — both now overstated. Issue a dated corrective supplement to identified recipients (with a recipient log and a board minute), and check reliance around the recent 5,572-share placement at $89.75. Sponsors/investors who received the draft IPO MOU receive the same correction."],
]

EYESEL_VIEW = [
    ["Ranked: 1st reject the FVH equity combination; 2nd proceed with Stage 1 only with the protection package; keep the BATNA visible",
     "Eyesel does not need this deal to survive — profitable, cash-generative, ₩10.36B retained earnings, and a strong BATNA as GenApep’s contract manufacturer (the $4/vial bottoming fee) capturing margin with none of the merger costs. What Eyesel lacks is growth and a story (FY2025 OP -31%): WBI’s MM Studio ramp, the AI-peptide/DPW technology and a listing are the honest rationale. The FVH combination asks Eyesel’s profits to fund a crowdfunding-stage company that is pre-revenue per the DD (1-K confirmation pending) — US opex alone equals 23–38% of Eyesel’s FY2025 operating profit."],
    ["The Eyesel protection package (conditions to Stage 1)",
     "Board majority matching 51% + reserved matters (route decision, any pool/option grant, related-party deals, US spend cap); dividend continuity (~₩300M/yr historic level) until listing proceeds; Eyesel cash ring-fenced — no upstream loans/guarantees; US costs funded exclusively from the external $2M raise; PCAOB audit fee capped and board-approved; chain-of-title CP satisfied before WBI technology value is credited; written Korean tax/FX opinion (one collective holdco filing, no dry tax for Eyesel’s shareholders) before any exchange."],
    ["Walk-away conditions",
     "No Route B step unless: FirstVitals proves reporting-company status on EDGAR, the 7.5M pool is cancelled or hard-capped, FVH enters at independently verified value with a fairness opinion, and every share flows pro rata to shareholder bodies (never 35% to any individual). DD the ₩435.0M FY2025 sales-commission counterparty before signing; disclose the DD report and cap table to the full Eyesel board (it has so far heard only the contradicted pitch, second-hand)."],
]

GOVERNANCE = [
    "Sidney Tam’s conflict must be squarely governed: he organized the meeting recommending FirstVitals, is the sole source of every now-contradicted FVH claim ($75M cap, GLP-1 technology, Medicare contracts), is a named sweat-pool beneficiary and is understood to hold the FA mandate and the Third-Director designation [confirm against the signed JV instruments]. Route-B advocacy and FVH verification must move to independent advisers; his recusal (Clause 3.6/3.8 machinery) applies to the route decision.",
    "Theresa Jang’s dual role: CEO-designate and, under the superseded draft MOU, personal recipient of 40% of FVH — the largest beneficiary of Route B as drafted — while acting as information conduit to the Eyesel principal. The block-entry rule (no individual allocations) and full disclosure resolve this; record it.",
    "“Brian” participates throughout the meeting record but appears on no attendee list, cap table or MOU — identify his role and mandate before board documents rely on his positions.",
    "DD provenance and good faith: the DD report is addressed to WBI only (author Hayley Zen — confirm mandate). Correct the $11.7M figure, then share the corrected report and the cap-table findings with the Eyesel board; a JV partner sitting on contradicting diligence is itself a good-faith problem.",
    "Do not sign, extend or reference the draft IPO-framework MOU: its Step-1 condition precedent can never be satisfied as written (no reporting status to “maintain”), its §5 GLP-1 “operating program” belongs to an abandoned service line, and its consolidated forecast carries $2.2M→$34M of unvalidated FVH revenue. It is formally superseded by this Plan v2.",
]

VERDICT = [
    ["Stage 1 JV (WBI × Eyesel)", "VIABLE — strengthened",
     "Eyesel’s verified financials close the data gap inside the equalisation band; 51:49 is defensible on evidence from both seats; proceed with the two drafting locks and the Eyesel protection package."],
    ["Route A (own F-1)", "VIABLE — conditional",
     "The default and fastest US path. Load-bearing conditions: sponsor pre-money > ~$25–35M, the $2M end-2026 bridge, US CEO and opex discipline. Test at the sponsor conversations; if the sponsor holds ~$18M, Route A destroys WBI value and Route C takes over."],
    ["Route B (FirstVitals)", "NOT VIABLE AS PITCHED",
     "Fails on the verified record: no reporting status (EDGAR-supported); pre-revenue with ~$500K lifetime capital per DD and the counterparty's own cap table (1-K/1-SA confirmation pending); no capital raised by a combination; no synergy; no time saving; a 54.18%-FD pool overhang; an asking anchor ≥37× the assessed supportable value. Optional at ~$0–2M with the pool cancelled — or as a commercial channel only."],
    ["Route C (KOSDAQ)", "VIABLE — develop now",
     "Meets profit tracks on Eyesel’s trailing actuals; solves the Korean tax/FX problem for both shareholder bodies; the fallback that protects the group’s negotiating position everywhere else."],
]

ACTIONS = [
    ["Now", "Sign Amendment No. 1 with the FX/reference-period locks + no-leakage covenant + principal confirmation; board minute superseding the draft IPO MOU; issue the one-pager corrective supplement."],
    ["This week", "FirstVitals gate-zero document requests (EDGAR index, 1-A status & amounts sold, 1-K/1-SA, note terms, entity chain); correct the DD report’s $11.7M; share corrected DD with the Eyesel board."],
    ["Before the Ernie Lee meetings", "Written US securities-counsel memo (reporting status, shell/Rule 144(i), seasoning); agree internally that no terms are discussed until gate-zero reports."],
    ["By Q4 2026", "Auditor appointed (IFRS primary, costed US GAAP option, capped fee); WBI evidence pack (NTS filing, H1-2026 actuals, MM Studio contracts); Eyesel balance sheet + commission-counterparty DD."],
    ["By end-2026", "$2M bridge closed into the holdco; KOSDAQ readiness memo (Route C) delivered to both boards."],
    ["Q1–Q2 2027", "Share exchange through the holdco block; route decision when sponsor + gate-zero + KOSDAQ memos are all on the table."],
]

# =============================== markdown ===============================

def wmd():
    L = []; a = L.append
    a("# GenApep — IPO Plan v2 (September 2026 revision)\n")
    a("> **%s**\n>\n> %s\n" % (CONF, DISCLAIMER))
    a("\n## 1. Why this revision — the new evidence\n\n| Document | What it establishes |\n|---|---|\n")
    for r in EVIDENCE: a("| %s | %s |\n" % (r[0], r[1]))
    a("\n**Bottom line.** The Eyesel data gap is closed favourably; the FirstVitals premise of the "
      "draft IPO MOU is contradicted by FirstVitals' own cap table and the DD record. Stage 1 (the "
      "WBI × Eyesel JV) is strengthened; Route B (FirstVitals) fails as pitched; Route A remains the "
      "default and a Korea listing is promoted to a formal parallel track.\n")
    a("\n## 2. FirstVitals — claimed vs verified\n\n| Claim in prior documents / the meeting | Verdict | Evidence |\n|---|---|---|\n")
    for r in FVH_CLAIMS: a("| %s | **%s** | %s |\n" % (r[0], r[1], r[2]))
    a("\n### Structural traps in the FirstVitals cap table\n")
    for t in FVH_STRUCTURE_TRAPS: a("- %s\n" % t)
    a("\n## 3. Eyesel — verified statutory financials (제19기 FY2025 / 제18기 FY2024)\n\n")
    a("| Line | FY2025 (@₩1,400/₩1,500) | FY2024 | Note |\n|---|---|---|---|\n")
    for r in EYESEL_TABLE: a("| %s | %s | %s | %s |\n" % tuple(r))
    a("\n")
    for t in EYESEL_READS: a("- %s\n" % t)
    a("\n## 4. WBI — the standardized figure set (correct $11.7M at source)\n\n| Figure | Value | Note |\n|---|---|---|\n")
    for r in WBI_FIGURES: a("| %s | %s | %s |\n" % tuple(r))
    a("\n## 5. The three routes — revised comparison\n\n| Route | Reality on the new evidence | Position |\n|---|---|---|\n")
    for r in ROUTES: a("| **%s** | %s | %s |\n" % tuple(r))
    a("\n## 6. The revised plan (route-independent core + gated decision)\n\n| Step | When | Content |\n|---|---|---|\n")
    for r in PLAN_STEPS: a("| **%s** | %s | %s |\n" % tuple(r))
    a("\n## 7. Viability from the WBI seat\n\n### Per-share outcomes (basis $89.75; 111,448 shares)\n\n| Scenario | $/share | Note |\n|---|---|---|\n")
    for r in WBI_PS: a("| %s | **%s** | %s |\n" % tuple(r))
    a("\n")
    for t, d in WBI_VIEW: a("- **%s** — %s\n" % (t, d))
    a("\n## 8. Viability from the Eyesel seat\n")
    for t, d in EYESEL_VIEW: a("- **%s** — %s\n" % (t, d))
    a("\n## 9. Governance & conflicts (to be minuted)\n")
    for i, t in enumerate(GOVERNANCE, 1): a("%d. %s\n" % (i, t))
    a("\n## 10. Verdict — possibility & viability\n\n| Component | Verdict | Basis |\n|---|---|---|\n")
    for r in VERDICT: a("| %s | **%s** | %s |\n" % tuple(r))
    a("\n## 11. Action list\n\n| When | Actions |\n|---|---|\n")
    for r in ACTIONS: a("| **%s** | %s |\n" % tuple(r))
    a("\n---\n*Analysis basis: 5-perspective multi-agent review with adversarial verification "
      "(16 Sep 2026). Figures recomputed from the statutory statements and the counterparty cap "
      "table; items marked [counsel to confirm] or 'implied' require primary verification.*\n")
    open(DIR + "ipo-plan-v2.md", "w").write("".join(L))

wmd()

# =============================== docx ===============================

def nd():
    doc = Document()
    n = doc.styles["Normal"]; n.font.name = "Calibri"; n.font.size = Pt(10.5)
    for lvl, sz in [("Heading 1", 16), ("Heading 2", 13), ("Heading 3", 11.5)]:
        st = doc.styles[lvl]; st.font.name = "Calibri"; st.font.size = Pt(sz)
        st.font.color.rgb = NAVY; st.font.bold = True
    return doc

def para(doc, t="", size=10.5, bold=False, italic=False, color=None, align=None, after=6):
    p = doc.add_paragraph()
    if align: p.alignment = align
    r = p.add_run(t); r.font.size = Pt(size); r.bold = bold; r.italic = italic
    if color: r.font.color.rgb = color
    p.paragraph_format.space_after = Pt(after); return p

def bullet(doc, t, lead=None):
    p = doc.add_paragraph(style="List Bullet")
    if lead:
        r = p.add_run(lead); r.bold = True
    p.add_run(t); p.paragraph_format.space_after = Pt(3); return p

def numbered(doc, t):
    p = doc.add_paragraph(style="List Number")
    p.add_run(t); p.paragraph_format.space_after = Pt(3); return p

def tbl(doc, headers, rows, widths=None, fs=9, hl_col=None):
    t = doc.add_table(rows=1, cols=len(headers)); t.style = "Light Grid Accent 1"
    t.alignment = WD_TABLE_ALIGNMENT.CENTER
    for i, h in enumerate(headers):
        r = t.rows[0].cells[i].paragraphs[0].add_run(str(h)); r.bold = True; r.font.size = Pt(fs)
    for row in rows:
        c = t.add_row().cells
        for i, v in enumerate(row):
            rr = c[i].paragraphs[0].add_run(str(v)); rr.font.size = Pt(fs)
            if i == 0 or i == hl_col: rr.bold = True
    if widths:
        for i, w in enumerate(widths):
            for r in t.rows: r.cells[i].width = Inches(w)
    doc.add_paragraph().paragraph_format.space_after = Pt(2); return t

doc = nd()
para(doc, "GENAPEP", size=26, bold=True, color=NAVY, align=WD_ALIGN_PARAGRAPH.CENTER, after=2)
para(doc, "IPO Plan v2 — September 2026 Revision & Viability Assessment",
     size=14, color=GREY, align=WD_ALIGN_PARAGRAPH.CENTER, after=2)
para(doc, CONF, size=9, bold=True, color=RED, align=WD_ALIGN_PARAGRAPH.CENTER, after=2)
para(doc, DISCLAIMER, size=8.5, italic=True, color=GREY, align=WD_ALIGN_PARAGRAPH.CENTER, after=10)

doc.add_heading("1. Why this revision — the new evidence", level=2)
tbl(doc, ["Document", "What it establishes"], EVIDENCE, widths=[3.4, 3.1])
para(doc, "Bottom line: the Eyesel data gap closes favourably; the FirstVitals premise of the draft "
          "IPO MOU is contradicted by FirstVitals' own cap table and the DD record. Stage 1 (the "
          "WBI × Eyesel JV) is strengthened; Route B fails as pitched; Route A remains the default "
          "and a Korea listing is promoted to a formal parallel track.", bold=True)

doc.add_heading("2. FirstVitals — claimed vs verified", level=2)
tbl(doc, ["Claim in prior documents / the meeting", "Verdict", "Evidence"], FVH_CLAIMS,
    widths=[2.0, 1.0, 3.5], hl_col=1)
doc.add_heading("Structural traps in the FirstVitals cap table", level=3)
for t in FVH_STRUCTURE_TRAPS:
    bullet(doc, t)

doc.add_heading("3. Eyesel — verified statutory financials (FY2025 / FY2024)", level=2)
tbl(doc, ["Line", "FY2025 (@₩1,400/₩1,500)", "FY2024", "Note"], EYESEL_TABLE,
    widths=[1.2, 1.7, 1.2, 2.4])
for t in EYESEL_READS:
    bullet(doc, t)

doc.add_heading("4. WBI — the standardized figure set", level=2)
tbl(doc, ["Figure", "Value", "Note"], WBI_FIGURES, widths=[2.2, 2.0, 2.3])

doc.add_heading("5. The three routes — revised comparison", level=2)
tbl(doc, ["Route", "Reality on the new evidence", "Position"], ROUTES, widths=[1.5, 2.6, 2.4])

doc.add_heading("6. The revised plan", level=2)
tbl(doc, ["Step", "When", "Content"], PLAN_STEPS, widths=[1.7, 1.0, 3.8])

doc.add_heading("7. Viability from the WBI seat", level=2)
doc.add_heading("Per-share outcomes (basis $89.75; 111,448 shares)", level=3)
tbl(doc, ["Scenario", "$/share", "Note"], WBI_PS, widths=[2.6, 0.9, 3.0], hl_col=1)
for t, d in WBI_VIEW:
    bullet(doc, d, t + " — ")

doc.add_heading("8. Viability from the Eyesel seat", level=2)
for t, d in EYESEL_VIEW:
    bullet(doc, d, t + " — ")

doc.add_heading("9. Governance & conflicts (to be minuted)", level=2)
for t in GOVERNANCE:
    numbered(doc, t)

doc.add_heading("10. Verdict — possibility & viability", level=2)
tbl(doc, ["Component", "Verdict", "Basis"], VERDICT, widths=[1.5, 1.4, 3.6], hl_col=1)

doc.add_heading("11. Action list", level=2)
tbl(doc, ["When", "Actions"], ACTIONS, widths=[1.4, 5.1])
para(doc, "Analysis basis: 5-perspective multi-agent review with adversarial verification "
          "(16 September 2026). Items marked [counsel to confirm] or 'implied' require primary "
          "verification before board reliance.", size=8.5, italic=True, color=GREY,
     align=WD_ALIGN_PARAGRAPH.CENTER)

doc.save(DIR + "GenApep_IPO_Plan_v2.docx")
print("Saved ipo-plan-v2.md, GenApep_IPO_Plan_v2.docx")
